### ISSUE TITLE
GPU Not Detected - RTX 4060 Ti (8GB)

### ISSUE THREAD

**Issue by TechMitten** [pinokiofactory/flux-webui#1]
I'm having a problem where it doesn't use my GPU to try generating the photo. I realize it should probably be more than 8gb, but wanted to mention the issue anyway.

**Comment by 6Morpheus6** [comment]
@techcow2 There is an updated version out now that needs less VRAM. Should be able to run on 12GB VRAM if the NVIDIA drivers aren't outdated. With 8GB it is in deed rather impossible sadly. To use the new flux-webui you should delete the old version in the first place.
Maybe you have a chance to run Flux in ComfyUI with 8GB if you use the 16GB flux model [Flux1d-16gb](https://civitai.com/models/623525/flux1d-16gb) and the image workflow published on X [Flux under 12GB VRAM](https://x.com/cocktailpeanut/status/1819482952071323788)
