### ISSUE TITLE
Out of Memory - RTX 4090 (24GB RAM)

### ISSUE THREAD

**Issue by skydiablo** [pinokiofactory/flux-webui#11]
Hi,
currently i'm trying to run the merged model on my 4090 (24GB RAM). but i got his error:

> torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacity of 23.61 GiB of which 45.06 MiB is free. Including non-PyTorch memory, this process has 22.69 GiB memory in use. Of the allocated memory 21.72 GiB is allocated by PyTorch, and 520.54 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

is that right, there is only 20MB missing? any suggestions of how can fix that and where should i set the configs?

regards, volker.

**Comment by skydiablo** [comment]
of, my fault, nevermind ;)

**Comment by underline9396** [comment]
@skydiablo how did you solve this?

**Comment by skydiablo** [comment]
oh, i dont know anymore, it is to fare away yet ;) sry...
